---
version: 2
jobs:
  build:
    docker:
      - image: jimmycuadra/rust
    steps:
      - checkout
      - run: apt-get update
      - run:
          name: Install ncurses-dev
          command: apt-get install libncurses-dev -y
      - run:
          name: Run cargo test
          command: cargo test
